# Web端
_BASE_PASSPORT_BILIBILI_COM="http://passport.bilibili.com"
_BASE_PASSPORT_BILIBILI_COM_QRCODE="%s/qrcode" % _BASE_PASSPORT_BILIBILI_COM
_BASE_PASSPORT_BILIBILI_COM_API="%s/api" % _BASE_PASSPORT_BILIBILI_COM
_BASE_PASSPORT_BILIBILI_COM_AJAX="%s/ajax" % _BASE_PASSPORT_BILIBILI_COM
# 首次请求获取已注册的sid和JSESSIONID
# 第二次带Cookies请求获取验证码图片以验证
CAPTCHA="%s/captcha" % _BASE_PASSPORT_BILIBILI_COM
LOGIN="%s/login" % _BASE_PASSPORT_BILIBILI_COM
MINILOGIN_LOGIN="%s/miniLogin/login" % _BASE_PASSPORT_BILIBILI_COM_AJAX
OAUTH = "%s/oauth" % _BASE_PASSPORT_BILIBILI_COM_API
GETLOGINURL="%s/getLoginUrl" % _BASE_PASSPORT_BILIBILI_COM_QRCODE
GETLOGININFO="%s/getLoginInfo" % _BASE_PASSPORT_BILIBILI_COM_QRCODE
# Client端
_BASE_ACCOUNT="https://account.bilibili.com"
_BASE_ACCOUNT_API="%s/api" % _BASE_ACCOUNT
LOGIN_V2="%s/login/v2" % _BASE_ACCOUNT_API
LOGIN_GET_KEY="%slogin/get_key" % _BASE_ACCOUNT_API
