from . import _BASE_INTERFACE_BILIBILI_COM,_BASE_API_BILIBILI_COM_X

COMMENT_BILIBILI_COM="https://comment.bilibili.com"
DMPOST="%s/dmpost" % _BASE_INTERFACE_BILIBILI_COM
RECALL="%s/dm/recall" % _BASE_API_BILIBILI_COM_X
