from . import _BASE_INTERFACE_BILIBILI_COM,_BASE_API_BILIBILI_COM_X,_BASE_WWW_BILIBILI_COM

ONLINE="%s/online" % _BASE_INTERFACE_BILIBILI_COM
WEB_SHOW_RES_LOC="%s/web-show/res/loc" % _BASE_API_BILIBILI_COM_X
WIDGET_GETSEARCHDEFAULTWORDS="%s/widget/getSearchDefaultWords" % _BASE_WWW_BILIBILI_COM