from . import _BASE_API_BILIBILI_COM_X

_BASE_SPACE_BILIBILI_COM="https://space.bilibili.com"
_BASE_SPACE_BILIBILI_COM_AJAX="%s/ajax" % _BASE_SPACE_BILIBILI_COM
_BASE_SPACE_BILIBILI_COM_AJAX_MEMBER="%s/member" % _BASE_SPACE_BILIBILI_COM_AJAX

TOPPHOTO_UPLOADTOPPHOTOV2="%s/topphoto/uploadTopPhotov2" % _BASE_SPACE_BILIBILI_COM_AJAX
WEB_SHOW_RES_LOC="%s/web-show/res/loc" % _BASE_API_BILIBILI_COM_X
MEMBER_GETINFO="%s/GetInfo" % _BASE_SPACE_BILIBILI_COM_AJAX_MEMBER
MEMBER_GETVIPINFO="%s/getVIPinfo"  % _BASE_SPACE_BILIBILI_COM_AJAX_MEMBER
MEMBER_GETVIPSTATUS="%s/getVipStatus" % _BASE_SPACE_BILIBILI_COM_AJAX_MEMBER
SIGN_SETSIGNV2="%s/sign/setSignv2" % _BASE_SPACE_BILIBILI_COM_AJAX
SETTING_GETNOTICE="%s/settings/getNotice" % _BASE_SPACE_BILIBILI_COM_AJAX
VIEWHISTORY_GETHISTORY="%s/viewhistory/gethistory" % _BASE_SPACE_BILIBILI_COM_AJAX