from . import _BASE_WEB_INTERFACE,_BASE_API_BILIBILI_COM_X,_BASE_API_BILIBILI_COM,_BASE_API_BILIBILI_COM_X_V2

CARD="%s/card" % _BASE_WEB_INTERFACE
NAV="%s/nav" % _BASE_WEB_INTERFACE
RELATION_STAT="%s/relation/stat" % _BASE_API_BILIBILI_COM_X
FAV_FOLDER="%s/fav/folder" % _BASE_API_BILIBILI_COM_X_V2